pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
    id("com.gradle.develocity") version("3.17.2")
}
develocity {
    buildScan {
        publishing.onlyIf { "true".equals(System.getProperty("envIsCi")) }
        uploadInBackground.set(!"true".equals(System.getProperty("envIsCi")))
        termsOfUseUrl.set("https://gradle.com/terms-of-service")
        termsOfUseAgree.set("yes")
    }
}

rootProject.name = "languagetool-parent"
include(":language-ar")
include(":language-br")
include(":language-ta")
include(":language-fr")
include(":language-de-DE-x-simple-language")
include(":language-it")
include(":language-en")
include(":language-lt")
include(":language-el")
include(":language-gl")
include(":languagetool-gui-commons")
include(":languagetool-dev")
include(":language-pt")
include(":language-sv")
include(":language-ml")
include(":language-nl")
include(":languagetool-commandline")
include(":languagetool-core")
include(":language-pl")
include(":languagetool-server")
include(":languagetool-standalone")
include(":languagetool-tools")
include(":languagetool-wikipedia")
include(":language-sl")
include(":language-tl")
include(":language-zh")
include(":language-es")
include(":language-eo")
include(":language-is")
include(":language-ru")
include(":language-be")
include(":language-km")
include(":language-de")
include(":language-ca")
include(":language-da")
include(":language-ro")
include(":language-fa")
include(":language-ga")
include(":language-sk")
include(":language-ja")
include(":language-uk")
include(":language-all")
include(":language-ast")
project(":language-ar").projectDir = file("languagetool-language-modules/ar")
project(":language-br").projectDir = file("languagetool-language-modules/br")
project(":language-ta").projectDir = file("languagetool-language-modules/ta")
project(":language-fr").projectDir = file("languagetool-language-modules/fr")
project(":language-de-DE-x-simple-language").projectDir = file("languagetool-language-modules/de-DE-x-simple-language")
project(":language-it").projectDir = file("languagetool-language-modules/it")
project(":language-en").projectDir = file("languagetool-language-modules/en")
project(":language-lt").projectDir = file("languagetool-language-modules/lt")
project(":language-el").projectDir = file("languagetool-language-modules/el")
project(":language-gl").projectDir = file("languagetool-language-modules/gl")
project(":language-pt").projectDir = file("languagetool-language-modules/pt")
project(":language-sv").projectDir = file("languagetool-language-modules/sv")
project(":language-ml").projectDir = file("languagetool-language-modules/ml")
project(":language-nl").projectDir = file("languagetool-language-modules/nl")
project(":language-pl").projectDir = file("languagetool-language-modules/pl")
project(":language-sl").projectDir = file("languagetool-language-modules/sl")
project(":language-tl").projectDir = file("languagetool-language-modules/tl")
project(":language-zh").projectDir = file("languagetool-language-modules/zh")
project(":language-es").projectDir = file("languagetool-language-modules/es")
project(":language-eo").projectDir = file("languagetool-language-modules/eo")
project(":language-is").projectDir = file("languagetool-language-modules/is")
project(":language-ru").projectDir = file("languagetool-language-modules/ru")
project(":language-be").projectDir = file("languagetool-language-modules/be")
project(":language-km").projectDir = file("languagetool-language-modules/km")
project(":language-de").projectDir = file("languagetool-language-modules/de")
project(":language-ca").projectDir = file("languagetool-language-modules/ca")
project(":language-da").projectDir = file("languagetool-language-modules/da")
project(":language-ro").projectDir = file("languagetool-language-modules/ro")
project(":language-fa").projectDir = file("languagetool-language-modules/fa")
project(":language-ga").projectDir = file("languagetool-language-modules/ga")
project(":language-sk").projectDir = file("languagetool-language-modules/sk")
project(":language-ja").projectDir = file("languagetool-language-modules/ja")
project(":language-uk").projectDir = file("languagetool-language-modules/uk")
project(":language-all").projectDir = file("languagetool-language-modules/all")
project(":language-ast").projectDir = file("languagetool-language-modules/ast")
