/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.languagetool.java-conventions")
}

dependencies {
    api(project(":language-de"))
    implementation(project(":languagetool-core"))
    implementation(libs.jetbrains.annotations)
    testImplementation(libs.junit4)
    testImplementation(testFixtures(project(":languagetool-core")))
    testImplementation(project(":languagetool-core"))
    testImplementation(libs.logback.classic)
}

setProperty("pomName", "Simple German module for LanguageTool")
description = "Simple German (\"Leichte Sprache\") is a variant of German supposed to be easy to understand. " +
        "There are some rules, but no formal definition or standard. " +
        "This module tries to implement some of those rules. " +
        "Details can be found, amongst others, at http://www.leichtesprache.org/"