/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.languagetool.java-conventions")
}

dependencies {
    api(project(":languagetool-core"))
    implementation(libs.jetbrains.annotations)
    testImplementation(libs.junit4)
    testImplementation(project(":languagetool-core"))
    testImplementation(testFixtures(project(":languagetool-core")))
    testImplementation(libs.logback.classic)
}

description = "Danish module for LanguageTool"
